services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    user: "user:user"
    volumes:
      - .:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ~/.gitconfig:/home/user/.gitconfig:ro
    hostname: dev
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - WAYLAND_DISPLAY=
      - XDG_SESSION_TYPE=x11
      - GDK_BACKEND=x11
      - QT_QPA_PLATFORM=xcb
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    ipc: host

    