stream_node:
  ros__parameters:
    port: 5000
    host: "10.0.0.1"
    bitrate: 400  # in kbps
    fps: 30
    encoder_type: "h265"
    preset: "low"
    width: 640
    height: 480
    test_enable: true
    arch: "nvidia"
    low:
      fps: 5
      bitrate: 500
      iframeinterval: 30

    medium:
      fps: 10
      bitrate: 500
      iframeinterval: 30

    high:
      fps: 20
      bitrate: 500
      iframeinterval: 30
