/**/stream:
  ros__parameters:
    port: 5000
    ip_address: "10.0.0.1"
    encoder_type: "h264"
    preset: "low"
    width: 640
    height: 480
    test_enable: false
    hardware: "pc"
    low:
      fps: 5
      bitrate: 200
      iframe_interval: 5
      vbv: 200

    medium:
      fps: 9
      bitrate: 350
      iframe_interval: 9
      vbv: 350

    high:
      fps: 9
      bitrate: 500
      iframe_interval: 9
      vbv: 500
