stream_node:
  ros__parameters:
    port: 5000
    host: "127.0.0.1"
    bitrate: 400  # in kbps
    fps: 30
    encoder_type: "h265"
    preset: "low"



    low:
      fps: 5
      bitrate: 500

    medium:
      fps: 10
      bitrate: 500

    high:
      fps: 20
      bitrate: 500
